

# ============================================================================>                   # production






spring.application.name=quora
server.port=${PORT:8080}

# --- Aiven MySQL connection ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jwt.secret=${SPRING_JWT_SECRET}
app.cors.local-origins=${LOCAL:http://localhost:5173}
app.cors.production-origins=${PRODUCTION:https://askverse-client.vercel.app}
app.cors.payment-origins=${PAYMENT_ORIGINS}
app.frontend.base-url=${APP_FRONTEND_BASE_URL}
app.auth.cookie-name=${APP_AUTH_COOKIE_NAME}
app.auth.cookie-secure=${APP_AUTH_COOKIE_SECURE}
app.auth.cookie-same-site=${APP_AUTH_COOKIE_SAME_SITE}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10


cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

app.subscription.default-currency=${APP_SUBSCRIPTION_DEFAULT_CURRENCY}
app.payment.default-gateway=${APP_PAYMENT_DEFAULT_GATEWAY}
razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}



